# Generated by Django 3.2.7 on 2021-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0002_auto_20210905_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='maakayuser',
            name='total_tip_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maakayuser',
            name='total_tip_sent',
            field=models.IntegerField(default=0),
        ),
    ]
