# Generated by Django 3.2.7 on 2021-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0003_auto_20210905_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='contender_accepted',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='referee_accepted',
        ),
        migrations.AddField(
            model_name='challenge',
            name='contender_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255),
        ),
        migrations.AddField(
            model_name='challenge',
            name='referee_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='NEW', max_length=255),
        ),
    ]
