# Generated by Django 3.2.7 on 2021-09-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0004_auto_20210907_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='uuid_hex',
            field=models.CharField(default='kjlksdlfjjldsfj', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
