# Generated by Django 3.2.7 on 2021-09-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0005_challenge_uuid_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='maakayuser',
            name='total_lost_in_challenges',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maakayuser',
            name='total_tip_received',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maakayuser',
            name='total_tip_sent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maakayuser',
            name='total_won_in_challenges',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maakayuser',
            name='total_won_in_tournaments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
