# Generated by Django 3.2.7 on 2021-09-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0007_remove_maakayuser_total_lost_in_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='referee',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=255),
        ),
    ]
