# Generated by Django 3.2.7 on 2021-09-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0008_auto_20210918_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='uuid_hex',
            field=models.CharField(default='fd026acdaaaaaaa', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
