# Generated by Django 3.2.7 on 2021-09-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_scantracker_total_scans'),
        ('maakay', '0009_tournament_uuid_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_winner', to='core.user'),
        ),
    ]
