# Generated by Django 3.2.7 on 2021-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0010_challenge_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertip',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
