# Generated by Django 3.2.7 on 2021-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0012_alter_usertip_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertip',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
