# Generated by Django 3.2.7 on 2021-09-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0013_alter_usertip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='maakayuser',
            name='total_amount_hosted',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maakayuser',
            name='total_challenges_hosted',
            field=models.BigIntegerField(default=0),
        ),
    ]
