# Generated by Django 3.2.7 on 2021-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='guild_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
