# Generated by Django 3.2.7 on 2021-11-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_guild_guild_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='withdrawal_address',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
