# Generated by Django 3.2.7 on 2021-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211113_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='has_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guild_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
