# Generated by Django 3.2.7 on 2021-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_guild_withdrawal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='withdrawal_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
