# Generated by Django 3.2.7 on 2021-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guildtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='tournament_channel_id',
        ),
    ]
