# Generated by Django 3.2.7 on 2021-11-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211107_1716'),
        ('core', '0004_alter_guild_withdrawal_address'),
    ]

    operations = [
    ]
