# Generated by Django 3.2.7 on 2021-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20211108_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='has_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
