# Generated by Django 3.2.7 on 2021-09-03 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guild_id', models.CharField(max_length=255)),
                ('tournament_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('withdrawal_address', models.CharField(blank=True, max_length=64, null=True)),
                ('total_fee_collected', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField()),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_balance', models.IntegerField()),
                ('total_fees_collected', models.IntegerField()),
                ('total_servers', models.IntegerField()),
                ('total_users', models.IntegerField()),
                ('total_challenges_hosted', models.IntegerField()),
                ('total_tournaments_hosted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_status', models.CharField(choices=[('WAITING_CONFIRMATION', 'Waiting Confirmation'), ('CONFIRMED', 'Confirmed')], max_length=255)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=255)),
                ('transaction_status', models.CharField(choices=[('NEW', 'New'), ('IDENTIFIED', 'Identified'), ('UNIDENTIFIED', 'Unidentified'), ('REFUNDED', 'Refunded')], max_length=255)),
                ('account_number', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField(default=0)),
                ('signature', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('memo', models.CharField(max_length=255)),
                ('total_confirmations', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_id', models.CharField(max_length=255, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('locked', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=255, unique=True)),
                ('withdrawal_address', models.CharField(blank=True, max_length=64, null=True)),
                ('total_won_in_challenges', models.IntegerField(default=0)),
                ('total_lost_in_challenges', models.IntegerField(default=0)),
                ('total_won_in_tournaments', models.IntegerField(default=0)),
                ('total_tournaments_won', models.IntegerField(default=0)),
                ('total_challenges_won', models.IntegerField(default=0)),
                ('total_referred', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=255)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=255)),
                ('hosted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hosted_by', to='main.user')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_referee', to='main.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('contender_accepted', models.BooleanField(default=False)),
                ('referee_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=255)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenger', to='main.user')),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contender', to='main.user')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_referee', to='main.user')),
            ],
        ),
    ]
