# Generated by Django 3.2.7 on 2021-10-01 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTip',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_recepient', to='core.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_sender', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_hex', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hosted_by', to='core.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='MaakayUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_won_in_challenges', models.BigIntegerField(default=0)),
                ('total_won_in_tournaments', models.BigIntegerField(default=0)),
                ('total_challenges_hosted', models.BigIntegerField(default=0)),
                ('total_amount_hosted', models.BigIntegerField(default=0)),
                ('total_tournaments_won', models.IntegerField(default=0)),
                ('total_challenges_won', models.IntegerField(default=0)),
                ('total_referred', models.IntegerField(default=0)),
                ('total_tip_sent', models.BigIntegerField(default=0)),
                ('total_tip_received', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_hex', models.CharField(max_length=255, unique=True)),
                ('amount', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('contender_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255)),
                ('referee_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ONGOING', 'Ongoing'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='NEW', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenger', to='core.user')),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contender', to='core.user')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_referee', to='core.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_winner', to='core.user')),
            ],
        ),
    ]
