# Generated by Django 3.2.7 on 2021-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maakay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertip',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
