# Generated by Django 3.2.6 on 2021-09-04 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guild_id', models.CharField(max_length=255)),
                ('trade_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dispute_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_role_id', models.CharField(blank=True, max_length=255, null=True)),
                ('withdrawal_address', models.CharField(blank=True, max_length=64, null=True)),
                ('total_fee_collected', models.IntegerField(default=0)),
                ('guild_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField()),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_balance', models.IntegerField()),
                ('total_fees_collected', models.IntegerField()),
                ('total_servers', models.IntegerField()),
                ('total_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_status', models.CharField(choices=[('WAITING_CONFIRMATION', 'Waiting Confirmation'), ('CONFIRMED', 'Confirmed')], max_length=255)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=255)),
                ('transaction_status', models.CharField(choices=[('NEW', 'New'), ('IDENTIFIED', 'Identified'), ('UNIDENTIFIED', 'Unidentified'), ('REFUNDED', 'Refunded')], max_length=255)),
                ('account_number', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('fee', models.IntegerField(default=0)),
                ('signature', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('memo', models.CharField(max_length=255)),
                ('total_confirmations', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_id', models.CharField(max_length=255, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('locked', models.IntegerField(default=0)),
                ('memo', models.CharField(max_length=255, unique=True)),
                ('withdrawal_address', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransactionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=255)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
        ),
    ]
