# Generated by Django 3.2.7 on 2021-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usertransactionhistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantracker',
            name='title',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
