# Generated by Django 3.2.7 on 2021-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_statistic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantracker',
            name='total_scans',
            field=models.IntegerField(default=0),
        ),
    ]
